# Generated by GitHub Copilot on 2026-01-21

from django.db import migrations, models


def _add_field_if_missing(
    apps,
    schema_editor,
    model_name: str,
    field_name: str,
    field: models.Field,
) -> None:
    model = apps.get_model("indy_hub", model_name)
    table_name = model._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }
    if field_name in existing_columns:
        return
    field.set_attributes_from_name(field_name)
    schema_editor.add_field(model, field)


def add_missing_columns(apps, schema_editor):
    _add_field_if_missing(
        apps,
        schema_editor,
        "charactersettings",
        "jobs_notify_custom_hours",
        models.PositiveSmallIntegerField(default=6),
    )
    _add_field_if_missing(
        apps,
        schema_editor,
        "charactersettings",
        "corp_jobs_notify_custom_hours",
        models.PositiveSmallIntegerField(default=6),
    )
    _add_field_if_missing(
        apps,
        schema_editor,
        "corporationsharingsetting",
        "corp_jobs_notify_custom_hours",
        models.PositiveSmallIntegerField(default=6),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0070_rename_cached_assets_tables"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="charactersettings",
                    name="jobs_notify_custom_hours",
                    field=models.PositiveSmallIntegerField(default=6),
                ),
                migrations.AddField(
                    model_name="charactersettings",
                    name="corp_jobs_notify_custom_hours",
                    field=models.PositiveSmallIntegerField(default=6),
                ),
                migrations.AddField(
                    model_name="corporationsharingsetting",
                    name="corp_jobs_notify_custom_hours",
                    field=models.PositiveSmallIntegerField(default=6),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_missing_columns, migrations.RunPython.noop),
            ],
        )
    ]
