# Generated by Django 4.2.23 on 2026-01-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indy_hub', '0071_add_job_notification_custom_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersettings',
            name='corp_jobs_notify_frequency',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('monthly', 'Monthly digest'), ('custom', 'Custom cadence'), ('custom_hours', 'Hourly digest')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='charactersettings',
            name='jobs_notify_frequency',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('monthly', 'Monthly digest'), ('custom', 'Custom cadence'), ('custom_hours', 'Hourly digest')], default='disabled', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporationsharingsetting',
            name='corp_jobs_notify_frequency',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('immediate', 'Immediate'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest'), ('monthly', 'Monthly digest'), ('custom', 'Custom cadence'), ('custom_hours', 'Hourly digest')], default='disabled', max_length=20),
        ),
    ]
