# Generated by ChatGPT on 2026-02-07

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0078_blueprintcopyoffer_source_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialExchangeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable the Material Exchange module",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Material Exchange Settings",
                "verbose_name_plural": "Material Exchange Settings",
                "default_permissions": (),
            },
        ),
    ]
