# Generated by Django 4.2 on 2026-02-20

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0083_setup_periodic_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialexchangesellorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Order Created - Awaiting Contract"),
                    ("awaiting_validation", "Awaiting Auth Validation"),
                    ("anomaly", "Anomaly - Waiting User/Admin Action"),
                    ("validated", "Validated - Awaiting Contract Accept"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="notify_admins_on_sell_anomaly",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, Material Hub admins are notified when a sell contract anomaly is detected.",
            ),
        ),
    ]
