# Generated by Django 4.2 on 2026-02-22

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0085_rename_permission_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialexchangesellorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Order Created - Awaiting Contract"),
                    ("awaiting_validation", "Awaiting Auth Validation"),
                    ("anomaly", "Anomaly - Waiting User/Admin Action"),
                    (
                        "anomaly_rejected",
                        "Anomaly - Contract Refused In-Game (Redo Required)",
                    ),
                    ("validated", "Validated - Awaiting Contract Accept"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
