# Generated by Django 4.2.27 on 2026-03-03 13:15

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0087_sdeindustryactivity_sdemarketgroup_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDESyncCompatState",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_source_build_number",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "last_source_release_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SDE Compat Sync State",
                "verbose_name_plural": "SDE Compat Sync State",
                "db_table": "indy_hub_sde_sync_state",
                "default_permissions": (),
            },
        ),
    ]
