# Generated by Django 4.2.27 on 2026-03-30 00:00

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0089_industry_structure_models"),
        ("eve_sde", "0014_dogmaeffect_description_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDEBlueprintActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        db_column="activity_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="indy_hub.sdeindustryactivity",
                    ),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        db_column="eve_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "SDE Blueprint Activity",
                "verbose_name_plural": "SDE Blueprint Activities",
                "db_table": "indy_hub_sdeblueprintactivity",
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["eve_type", "activity"],
                        name="indy_hub_sd_eve_typ_6e34d2_idx",
                    )
                ],
                "unique_together": {("eve_type", "activity")},
            },
        ),
    ]
