# Generated by GitHub Copilot

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0092_corporationsharingsetting_blueprint_catalog_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="blueprintcopyoffer",
            name="proposed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="blueprintcopyoffer",
            name="proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blueprintcopyoffer",
            name="proposed_by_role",
            field=models.CharField(
                blank=True,
                choices=[("buyer", "Buyer"), ("seller", "Builder")],
                max_length=16,
            ),
        ),
    ]
