# Generated by Django 4.2.23 on 2026-04-24 16:27

# Standard Library
import secrets
from decimal import Decimal, InvalidOperation

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

PROJECT_REF_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"
PROJECT_REF_LENGTH = 10


def _table_exists(schema_editor, table_name):
    return table_name in schema_editor.connection.introspection.table_names()


class SafeDeleteModel(migrations.DeleteModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.name)
        if _table_exists(schema_editor, model._meta.db_table):
            schema_editor.delete_model(model)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        if not _table_exists(schema_editor, model._meta.db_table):
            schema_editor.create_model(model)


def _build_legacy_workspace_state(simulation):
    return {
        "blueprint_type_id": int(simulation.blueprint_type_id or 0),
        "blueprint_name": simulation.blueprint_name,
        "runs": max(1, int(simulation.runs or 1)),
        "simulation_name": simulation.simulation_name,
        "active_tab": simulation.active_tab or "materials",
        "items": [
            {
                "type_id": int(config.item_type_id),
                "mode": str(config.production_mode or "prod"),
                "quantity": int(config.quantity_needed or 0),
            }
            for config in simulation.production_configs.all().order_by("item_type_id")
        ],
        "blueprint_efficiencies": [
            {
                "blueprint_type_id": int(eff.blueprint_type_id),
                "material_efficiency": int(eff.material_efficiency or 0),
                "time_efficiency": int(eff.time_efficiency or 0),
            }
            for eff in simulation.blueprint_efficiencies.all().order_by(
                "blueprint_type_id"
            )
        ],
        "custom_prices": [
            {
                "item_type_id": int(price.item_type_id),
                "unit_price": float(price.unit_price or 0),
                "is_sale_price": bool(price.is_sale_price),
            }
            for price in simulation.custom_prices.all().order_by("item_type_id")
        ],
        "estimated_cost": float(simulation.estimated_cost or 0),
        "estimated_revenue": float(simulation.estimated_revenue or 0),
        "estimated_profit": float(simulation.estimated_profit or 0),
        "total_items": int(simulation.total_items or 0),
        "total_buy_items": int(simulation.total_buy_items or 0),
        "total_prod_items": int(simulation.total_prod_items or 0),
    }


def _next_project_ref(production_project_model):
    for _attempt in range(32):
        candidate = "".join(
            secrets.choice(PROJECT_REF_ALPHABET) for _char in range(PROJECT_REF_LENGTH)
        )
        if not production_project_model.objects.filter(project_ref=candidate).exists():
            return candidate
    raise RuntimeError("Unable to allocate a unique production project reference.")


def _get_type_name(connection, type_id):
    if not type_id:
        return ""

    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT name FROM eve_sde_itemtype WHERE id = %s AND COALESCE(published, 0) = 1 LIMIT 1",
            [int(type_id)],
        )
        row = cursor.fetchone()
    return str(row[0]) if row and row[0] else ""


def _get_blueprint_product_row(connection, blueprint_type_id):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT p.product_eve_type_id, p.quantity
            FROM indy_hub_sdeindustryactivityproduct p
            JOIN eve_sde_itemtype blueprint_t ON blueprint_t.id = p.eve_type_id
            JOIN eve_sde_itemtype product_t ON product_t.id = p.product_eve_type_id
            WHERE p.eve_type_id = %s
                        AND p.activity_id IN (1, 11)
                        AND COALESCE(blueprint_t.published, 0) = 1
                        AND COALESCE(product_t.published, 0) = 1
            ORDER BY CASE activity_id WHEN 1 THEN 0 WHEN 11 THEN 1 ELSE 99 END
            LIMIT 1
            """,
            [int(blueprint_type_id)],
        )
        row = cursor.fetchone()

    if not row:
        return None, 1
    product_type_id = int(row[0]) if row[0] else None
    output_quantity = max(1, int((row[1] if row[1] else 1) or 1))
    return product_type_id, output_quantity


def _coerce_int(value, default=0):
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _coerce_decimal(value, default="0"):
    try:
        return Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError):
        return Decimal(default)


def _coerce_workspace_rows(raw_rows):
    return raw_rows if isinstance(raw_rows, list) else []


def _normalize_legacy_mode(mode):
    normalized_mode = str(mode or "prod").strip().lower()
    if normalized_mode in {"produce", "prod"}:
        return "prod"
    if normalized_mode == "buy":
        return "buy"
    return "useless"


def _derive_reverse_workspace_items(project, selected_items):
    workspace_items = _coerce_workspace_rows(
        (project.workspace_state or {}).get("items")
    )
    if workspace_items:
        return workspace_items

    derived_items = []
    for item in selected_items:
        item_type_id = _coerce_int(item.type_id, 0)
        if item_type_id <= 0:
            continue
        derived_items.append(
            {
                "type_id": item_type_id,
                "mode": _normalize_legacy_mode(item.inclusion_mode),
                "quantity": max(0, _coerce_int(item.quantity_requested, 0)),
                "blueprint_type_id": _coerce_int(item.blueprint_type_id, 0) or None,
            }
        )
    return derived_items


def _derive_reverse_blueprint_efficiencies(project, selected_items, blueprint_type_id):
    workspace_rows = _coerce_workspace_rows(
        (project.workspace_state or {}).get("blueprint_efficiencies")
    )
    if workspace_rows:
        return workspace_rows

    blueprint_ids = []
    for item in selected_items:
        item_blueprint_type_id = _coerce_int(item.blueprint_type_id, 0)
        if item_blueprint_type_id > 0 and item_blueprint_type_id not in blueprint_ids:
            blueprint_ids.append(item_blueprint_type_id)

    if blueprint_type_id > 0 and blueprint_type_id not in blueprint_ids:
        blueprint_ids.append(blueprint_type_id)

    return [
        {
            "blueprint_type_id": item_blueprint_type_id,
            "material_efficiency": 0,
            "time_efficiency": 0,
        }
        for item_blueprint_type_id in blueprint_ids
    ]


def _fallback_legacy_blueprint_type_id(project_id):
    return 900000000000 + max(1, int(project_id or 1))


def _resolve_reverse_blueprint_context(project, selected_items, connection):
    workspace_state = dict(project.workspace_state or {})
    workspace_items = _derive_reverse_workspace_items(project, selected_items)
    primary_selected_item = next(
        (item for item in selected_items if _coerce_int(item.blueprint_type_id, 0) > 0),
        selected_items[0] if selected_items else None,
    )
    primary_workspace_item = workspace_items[0] if workspace_items else {}

    blueprint_type_id = _coerce_int(workspace_state.get("blueprint_type_id"), 0)
    if blueprint_type_id <= 0:
        blueprint_type_id = _coerce_int(
            primary_workspace_item.get("blueprint_type_id"), 0
        )
    if blueprint_type_id <= 0 and primary_selected_item is not None:
        blueprint_type_id = _coerce_int(primary_selected_item.blueprint_type_id, 0)
    if blueprint_type_id <= 0 and primary_selected_item is not None:
        blueprint_type_id = _coerce_int(primary_selected_item.type_id, 0)
    if blueprint_type_id <= 0:
        blueprint_type_id = _fallback_legacy_blueprint_type_id(project.id)

    primary_quantity = max(
        1,
        _coerce_int(
            workspace_state.get("runs"),
            _coerce_int(
                primary_workspace_item.get("quantity"),
                _coerce_int(
                    getattr(primary_selected_item, "quantity_requested", 0),
                    1,
                ),
            ),
        ),
    )
    _product_type_id, output_quantity = _get_blueprint_product_row(
        connection,
        blueprint_type_id,
    )
    runs = max(
        1,
        _coerce_int(
            workspace_state.get("runs"),
            (primary_quantity + max(1, output_quantity) - 1) // max(1, output_quantity),
        ),
    )

    blueprint_name = str(
        workspace_state.get("blueprint_name")
        or _get_type_name(connection, blueprint_type_id)
        or getattr(primary_selected_item, "type_name", "")
        or project.source_name
        or project.name
        or blueprint_type_id
    )[:255]
    simulation_name = str(
        workspace_state.get("simulation_name")
        or project.name
        or blueprint_name
        or blueprint_type_id
    )[:255]

    return {
        "blueprint_type_id": blueprint_type_id,
        "blueprint_name": blueprint_name,
        "runs": runs,
        "simulation_name": simulation_name,
        "workspace_items": workspace_items,
    }


def _allocate_reverse_runs(
    production_simulation_model, user_id, blueprint_type_id, runs
):
    candidate_runs = max(1, int(runs or 1))
    while production_simulation_model.objects.filter(
        user_id=user_id,
        blueprint_type_id=blueprint_type_id,
        runs=candidate_runs,
    ).exists():
        candidate_runs += 1
    return candidate_runs


def migrate_legacy_simulations_to_projects(apps, schema_editor):
    ProductionSimulation = apps.get_model("indy_hub", "ProductionSimulation")
    ProductionProject = apps.get_model("indy_hub", "ProductionProject")
    ProductionProjectItem = apps.get_model("indy_hub", "ProductionProjectItem")

    connection = schema_editor.connection
    simulations = list(
        ProductionSimulation.objects.all()
        .order_by("id")
        .prefetch_related(
            "production_configs",
            "blueprint_efficiencies",
            "custom_prices",
        )
    )
    if not simulations:
        return

    for simulation in simulations:
        blueprint_type_id = int(simulation.blueprint_type_id or 0)
        product_type_id, output_quantity = _get_blueprint_product_row(
            connection,
            blueprint_type_id,
        )
        requested_runs = max(1, int(simulation.runs or 1))
        final_quantity = max(1, requested_runs * output_quantity)
        product_name = _get_type_name(connection, product_type_id)
        blueprint_name = str(simulation.blueprint_name or "")
        project_name = str(
            simulation.simulation_name
            or product_name
            or blueprint_name
            or blueprint_type_id
        )[:255]
        project_ref = _next_project_ref(ProductionProject)

        summary = {
            "selected_items": 1,
            "selected_quantity": final_quantity,
            "craftable_items": 1,
            "buy_items": 0,
            "legacy_simulation_id": simulation.id,
        }
        workspace_state = _build_legacy_workspace_state(simulation)

        project = ProductionProject.objects.create(
            user_id=simulation.user_id,
            project_ref=project_ref,
            name=project_name,
            status="saved",
            source_kind="manual",
            source_text=blueprint_name,
            source_name=blueprint_name,
            notes="Migrated during 0096 from legacy single-blueprint simulations.",
            summary=summary,
            workspace_state=workspace_state,
        )
        ProductionProject.objects.filter(pk=project.pk).update(
            created_at=simulation.created_at,
            updated_at=simulation.updated_at,
        )

        item = ProductionProjectItem.objects.create(
            project_id=project.id,
            type_id=product_type_id or blueprint_type_id,
            type_name=product_name or blueprint_name or str(blueprint_type_id),
            quantity_requested=final_quantity,
            category_key="manual",
            category_label="Manual list",
            category_order=90,
            source_line=product_name or blueprint_name or str(blueprint_type_id),
            is_selected=True,
            is_craftable=True,
            inclusion_mode="produce",
            blueprint_type_id=blueprint_type_id or None,
            metadata={"legacy_simulation_id": simulation.id},
        )
        ProductionProjectItem.objects.filter(pk=item.pk).update(
            created_at=simulation.created_at,
            updated_at=simulation.updated_at,
        )


def reverse_projects_to_legacy_simulations(apps, schema_editor):
    ProductionSimulation = apps.get_model("indy_hub", "ProductionSimulation")
    ProductionConfig = apps.get_model("indy_hub", "ProductionConfig")
    BlueprintEfficiency = apps.get_model("indy_hub", "BlueprintEfficiency")
    CustomPrice = apps.get_model("indy_hub", "CustomPrice")
    ProductionProject = apps.get_model("indy_hub", "ProductionProject")

    connection = schema_editor.connection
    projects = list(
        ProductionProject.objects.all().order_by("id").prefetch_related("items")
    )
    if not projects:
        return

    for project in projects:
        selected_items = [
            item
            for item in project.items.all().order_by("category_order", "id")
            if item.is_selected and str(item.inclusion_mode or "") != "skip"
        ]
        context = _resolve_reverse_blueprint_context(
            project, selected_items, connection
        )
        blueprint_type_id = int(context["blueprint_type_id"])
        workspace_items = context["workspace_items"]
        blueprint_efficiencies = _derive_reverse_blueprint_efficiencies(
            project,
            selected_items,
            blueprint_type_id,
        )
        custom_prices = _coerce_workspace_rows(
            (project.workspace_state or {}).get("custom_prices")
        )

        total_items = max(
            0,
            _coerce_int(
                (project.workspace_state or {}).get("total_items"), len(workspace_items)
            ),
        )
        total_buy_items = max(
            0,
            _coerce_int(
                (project.workspace_state or {}).get("total_buy_items"),
                sum(
                    1
                    for item in workspace_items
                    if _normalize_legacy_mode(item.get("mode")) == "buy"
                ),
            ),
        )
        total_prod_items = max(
            0,
            _coerce_int(
                (project.workspace_state or {}).get("total_prod_items"),
                sum(
                    1
                    for item in workspace_items
                    if _normalize_legacy_mode(item.get("mode")) == "prod"
                ),
            ),
        )

        preferred_simulation_id = _coerce_int(
            (project.summary or {}).get("legacy_simulation_id"),
            0,
        )
        create_kwargs = {
            "user_id": project.user_id,
            "blueprint_type_id": blueprint_type_id,
            "blueprint_name": context["blueprint_name"],
            "runs": _allocate_reverse_runs(
                ProductionSimulation,
                project.user_id,
                blueprint_type_id,
                context["runs"],
            ),
            "simulation_name": context["simulation_name"],
            "total_items": total_items,
            "total_buy_items": total_buy_items,
            "total_prod_items": total_prod_items,
            "estimated_cost": _coerce_decimal(
                (project.workspace_state or {}).get("estimated_cost"),
            ),
            "estimated_revenue": _coerce_decimal(
                (project.workspace_state or {}).get("estimated_revenue"),
            ),
            "estimated_profit": _coerce_decimal(
                (project.workspace_state or {}).get("estimated_profit"),
            ),
            "active_tab": str(
                (project.workspace_state or {}).get("active_tab") or "materials"
            )[:50],
        }
        if (
            preferred_simulation_id > 0
            and not ProductionSimulation.objects.filter(
                pk=preferred_simulation_id
            ).exists()
        ):
            create_kwargs["id"] = preferred_simulation_id

        simulation = ProductionSimulation.objects.create(**create_kwargs)
        ProductionSimulation.objects.filter(pk=simulation.pk).update(
            created_at=project.created_at,
            updated_at=project.updated_at,
        )

        aggregated_configs = {}
        for item in workspace_items:
            item_type_id = _coerce_int(item.get("type_id"), 0)
            if item_type_id <= 0:
                continue
            config = aggregated_configs.setdefault(
                item_type_id,
                {
                    "blueprint_type_id": _coerce_int(
                        item.get("blueprint_type_id"),
                        blueprint_type_id,
                    )
                    or blueprint_type_id,
                    "production_mode": _normalize_legacy_mode(item.get("mode")),
                    "quantity_needed": 0,
                },
            )
            config["quantity_needed"] += max(0, _coerce_int(item.get("quantity"), 0))
            config["production_mode"] = _normalize_legacy_mode(
                item.get("mode") or config["production_mode"]
            )
        for item_type_id, config in aggregated_configs.items():
            ProductionConfig.objects.create(
                user_id=project.user_id,
                simulation_id=simulation.id,
                blueprint_type_id=config["blueprint_type_id"],
                item_type_id=item_type_id,
                production_mode=config["production_mode"],
                quantity_needed=config["quantity_needed"],
                runs=simulation.runs,
            )

        created_blueprint_ids = set()
        for efficiency in blueprint_efficiencies:
            efficiency_blueprint_type_id = _coerce_int(
                efficiency.get("blueprint_type_id"),
                0,
            )
            if (
                efficiency_blueprint_type_id <= 0
                or efficiency_blueprint_type_id in created_blueprint_ids
            ):
                continue
            created_blueprint_ids.add(efficiency_blueprint_type_id)
            BlueprintEfficiency.objects.create(
                user_id=project.user_id,
                simulation_id=simulation.id,
                blueprint_type_id=efficiency_blueprint_type_id,
                material_efficiency=max(
                    0,
                    min(_coerce_int(efficiency.get("material_efficiency"), 0), 10),
                ),
                time_efficiency=max(
                    0,
                    min(_coerce_int(efficiency.get("time_efficiency"), 0), 20),
                ),
            )

        created_price_ids = set()
        for custom_price in custom_prices:
            item_type_id = _coerce_int(custom_price.get("item_type_id"), 0)
            if item_type_id <= 0 or item_type_id in created_price_ids:
                continue
            created_price_ids.add(item_type_id)
            CustomPrice.objects.create(
                user_id=project.user_id,
                simulation_id=simulation.id,
                item_type_id=item_type_id,
                unit_price=_coerce_decimal(custom_price.get("unit_price")),
                is_sale_price=bool(custom_price.get("is_sale_price")),
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("indy_hub", "0095_materialexchangeacceptedlocation_and_type_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_ref",
                    models.CharField(
                        blank=True, editable=False, max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "In progress"),
                            ("saved", "Saved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("eft", "EFT fitting"),
                            ("manual", "Manual list"),
                            ("mixed", "Mixed"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("source_text", models.TextField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("workspace_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProductionProjectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.BigIntegerField(blank=True, null=True)),
                ("type_name", models.CharField(max_length=255)),
                ("quantity_requested", models.BigIntegerField(default=1)),
                ("category_key", models.CharField(blank=True, max_length=64)),
                ("category_label", models.CharField(blank=True, max_length=255)),
                ("category_order", models.IntegerField(default=0)),
                ("source_line", models.TextField(blank=True)),
                ("is_selected", models.BooleanField(default=True)),
                ("is_craftable", models.BooleanField(default=False)),
                (
                    "inclusion_mode",
                    models.CharField(
                        choices=[
                            ("produce", "Produce"),
                            ("buy", "Buy"),
                            ("skip", "Skip"),
                        ],
                        default="produce",
                        max_length=16,
                    ),
                ),
                ("blueprint_type_id", models.BigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category_order", "type_name", "id"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="productionprojectitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="indy_hub.productionproject",
            ),
        ),
        migrations.AddField(
            model_name="productionproject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "is_selected"], name="indy_hub_pr_project_a2d58a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "inclusion_mode"],
                name="indy_hub_pr_project_97f750_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "type_id"], name="indy_hub_pr_project_f01f60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionprojectitem",
            constraint=models.UniqueConstraint(
                fields=("project", "type_id", "category_key"),
                name="indy_hub_project_item_unique_type_category",
            ),
        ),
        migrations.AddIndex(
            model_name="productionproject",
            index=models.Index(
                fields=["user", "status", "-updated_at"],
                name="indy_hub_pr_user_id_a57633_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionproject",
            index=models.Index(
                fields=["user", "source_kind", "-updated_at"],
                name="indy_hub_pr_user_id_a7a32a_idx",
            ),
        ),
        migrations.RunPython(
            migrate_legacy_simulations_to_projects,
            reverse_code=reverse_projects_to_legacy_simulations,
        ),
        SafeDeleteModel(
            name="BlueprintEfficiency",
        ),
        SafeDeleteModel(
            name="CustomPrice",
        ),
        SafeDeleteModel(
            name="ProductionConfig",
        ),
        SafeDeleteModel(
            name="ProductionSimulation",
        ),
    ]
