# Generated by Django 4.2.23 on 2026-04-24 16:27

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("indy_hub", "0095_materialexchangeacceptedlocation_and_type_filters"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_ref",
                    models.CharField(
                        blank=True, editable=False, max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "In progress"),
                            ("saved", "Saved"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("eft", "EFT fitting"),
                            ("manual", "Manual list"),
                            ("mixed", "Mixed"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("source_text", models.TextField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("workspace_state", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProductionProjectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.BigIntegerField(blank=True, null=True)),
                ("type_name", models.CharField(max_length=255)),
                ("quantity_requested", models.BigIntegerField(default=1)),
                ("category_key", models.CharField(blank=True, max_length=64)),
                ("category_label", models.CharField(blank=True, max_length=255)),
                ("category_order", models.IntegerField(default=0)),
                ("source_line", models.TextField(blank=True)),
                ("is_selected", models.BooleanField(default=True)),
                ("is_craftable", models.BooleanField(default=False)),
                (
                    "inclusion_mode",
                    models.CharField(
                        choices=[
                            ("produce", "Produce"),
                            ("buy", "Buy"),
                            ("skip", "Skip"),
                        ],
                        default="produce",
                        max_length=16,
                    ),
                ),
                ("blueprint_type_id", models.BigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category_order", "type_name", "id"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="productionprojectitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="indy_hub.productionproject",
            ),
        ),
        migrations.AddField(
            model_name="productionproject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="production_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "is_selected"], name="indy_hub_pr_project_a2d58a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "inclusion_mode"],
                name="indy_hub_pr_project_97f750_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionprojectitem",
            index=models.Index(
                fields=["project", "type_id"], name="indy_hub_pr_project_f01f60_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productionprojectitem",
            constraint=models.UniqueConstraint(
                fields=("project", "type_id", "category_key"),
                name="indy_hub_project_item_unique_type_category",
            ),
        ),
        migrations.AddIndex(
            model_name="productionproject",
            index=models.Index(
                fields=["user", "status", "-updated_at"],
                name="indy_hub_pr_user_id_a57633_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productionproject",
            index=models.Index(
                fields=["user", "source_kind", "-updated_at"],
                name="indy_hub_pr_user_id_a7a32a_idx",
            ),
        ),
    ]
