# Generated by Django 4.2.23 on 2026-04-26 20:27

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0098_align_corporation_sharing_choices"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="industrystructure",
            new_name="indy_hub_in_constel_30b149_idx",
            old_name="indy_hub_in_constel_22f76f_idx",
        ),
        migrations.RenameIndex(
            model_name="industrystructure",
            new_name="indy_hub_in_region__db733f_idx",
            old_name="indy_hub_in_region__8e4ef4_idx",
        ),
        migrations.RenameIndex(
            model_name="industrystructure",
            new_name="indy_hub_in_visibil_c32ce1_idx",
            old_name="indy_hub_in_visibili_215887_idx",
        ),
        migrations.RenameIndex(
            model_name="industrystructure",
            new_name="indy_hub_in_source__b435e9_idx",
            old_name="indy_hub_in_source__2f4ab3_idx",
        ),
        migrations.RenameIndex(
            model_name="sdeblueprintactivity",
            new_name="indy_hub_sd_eve_typ_366e41_idx",
            old_name="indy_hub_sd_eve_typ_6e34d2_idx",
        ),
    ]
