# Generated by Django 4.2.23 on 2026-04-26 20:27

# Django
from django.db import migrations


def _table_constraints(schema_editor, table_name: str) -> set[str]:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(cursor, table_name)
    return set(constraints.keys())


def _rename_index_if_needed(
    schema_editor,
    *,
    table_name: str,
    old_name: str,
    new_name: str,
) -> None:
    connection = schema_editor.connection
    existing = _table_constraints(schema_editor, table_name)
    if new_name in existing or old_name not in existing:
        return

    with connection.cursor() as cursor:
        constraint_map = connection.introspection.get_constraints(cursor, table_name)
    old_info = constraint_map.get(old_name, {})
    columns = old_info.get("columns") or []
    unique = bool(old_info.get("unique"))

    quoted_table = schema_editor.quote_name(table_name)
    quoted_old = schema_editor.quote_name(old_name)
    quoted_new = schema_editor.quote_name(new_name)

    vendor = connection.vendor
    if vendor == "mysql":
        schema_editor.execute(
            f"ALTER TABLE {quoted_table} RENAME INDEX {quoted_old} TO {quoted_new}"
        )
        return

    if vendor == "postgresql":
        schema_editor.execute(f"ALTER INDEX {quoted_old} RENAME TO {quoted_new}")
        return

    # SQLite and any backend without native rename-index support.
    if not columns:
        return
    quoted_cols = ", ".join(schema_editor.quote_name(column) for column in columns)
    unique_sql = "UNIQUE " if unique else ""
    schema_editor.execute(f"DROP INDEX {quoted_old}")
    schema_editor.execute(
        f"CREATE {unique_sql}INDEX {quoted_new} ON {quoted_table} ({quoted_cols})"
    )


def _forwards(apps, schema_editor):
    # `RenameIndex` fails on environments where the old index names were
    # already aligned manually or by backend-specific name normalization.
    rename_specs = [
        (
            "indy_hub_industrystructure",
            "indy_hub_in_constel_22f76f_idx",
            "indy_hub_in_constel_30b149_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_region__8e4ef4_idx",
            "indy_hub_in_region__db733f_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_visibili_215887_idx",
            "indy_hub_in_visibil_c32ce1_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_source__2f4ab3_idx",
            "indy_hub_in_source__b435e9_idx",
        ),
        (
            "indy_hub_sdeblueprintactivity",
            "indy_hub_sd_eve_typ_6e34d2_idx",
            "indy_hub_sd_eve_typ_366e41_idx",
        ),
    ]

    for table_name, old_name, new_name in rename_specs:
        _rename_index_if_needed(
            schema_editor,
            table_name=table_name,
            old_name=old_name,
            new_name=new_name,
        )


def _backwards(apps, schema_editor):
    reverse_specs = [
        (
            "indy_hub_industrystructure",
            "indy_hub_in_constel_30b149_idx",
            "indy_hub_in_constel_22f76f_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_region__db733f_idx",
            "indy_hub_in_region__8e4ef4_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_visibil_c32ce1_idx",
            "indy_hub_in_visibili_215887_idx",
        ),
        (
            "indy_hub_industrystructure",
            "indy_hub_in_source__b435e9_idx",
            "indy_hub_in_source__2f4ab3_idx",
        ),
        (
            "indy_hub_sdeblueprintactivity",
            "indy_hub_sd_eve_typ_366e41_idx",
            "indy_hub_sd_eve_typ_6e34d2_idx",
        ),
    ]

    for table_name, old_name, new_name in reverse_specs:
        _rename_index_if_needed(
            schema_editor,
            table_name=table_name,
            old_name=old_name,
            new_name=new_name,
        )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("indy_hub", "0098_align_corporation_sharing_choices"),
    ]

    operations = [
        migrations.RunPython(_forwards, _backwards),
    ]
