# Generated by Django 4.2.27 on 2026-06-06

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0100_repair_blueprint_bp_type_classification"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sdeindustryactivityproduct",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sdeindustryactivitymaterial",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sdeblueprintactivity",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sdeindustryactivity",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sdemarketgroup",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS indy_hub_sde_sync_state",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
