# Generated by Django 4.2.27 on 2026-06-06

# Django
from django.db import migrations


def _noop(_apps, _schema_editor):
    """Forward migration intentionally does nothing."""


def _ensure_legacy_tables_for_rollback(_apps, schema_editor):
    """Recreate minimal legacy tables needed when rolling back below 0101.

    Migration 0101 drops legacy SDE compatibility tables with irreversible SQL.
    Some historical migrations (notably 0096/0099) still reference these tables
    during backwards/forwards test round-trips. On rollback from latest, we
    recreate a minimal compatible shape so those historical migrations can run.
    """

    connection = schema_editor.connection
    table_names = set(connection.introspection.table_names())

    if "indy_hub_sdeindustryactivityproduct" not in table_names:
        schema_editor.execute(
            """
            CREATE TABLE indy_hub_sdeindustryactivityproduct (
                id INTEGER PRIMARY KEY,
                eve_type_id BIGINT NOT NULL,
                activity_id INTEGER NOT NULL,
                product_eve_type_id BIGINT NOT NULL,
                quantity INTEGER NOT NULL DEFAULT 1
            )
            """
        )

    if "indy_hub_sdeblueprintactivity" not in table_names:
        schema_editor.execute(
            """
            CREATE TABLE indy_hub_sdeblueprintactivity (
                id INTEGER PRIMARY KEY,
                eve_type_id BIGINT NOT NULL,
                activity VARCHAR(32) NOT NULL
            )
            """
        )

    with connection.cursor() as cursor:
        constraints = connection.introspection.get_constraints(
            cursor,
            "indy_hub_sdeblueprintactivity",
        )

    if "indy_hub_sd_eve_typ_366e41_idx" not in constraints:
        schema_editor.execute(
            """
            CREATE INDEX indy_hub_sd_eve_typ_366e41_idx
            ON indy_hub_sdeblueprintactivity (eve_type_id, activity)
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0101_drop_legacy_indy_sde_tables"),
    ]

    operations = [
        migrations.RunPython(
            code=_noop, reverse_code=_ensure_legacy_tables_for_rollback
        ),
    ]
