# Generated by Django 4.2.27 on 2026-07-09

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0102_rollback_compat_legacy_sde_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialexchangesellorder",
            name="character_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="EVE character ID used to create this sell order",
                null=True,
            ),
        ),
    ]
