# Generated by Django 4.2.27 on 2026-07-11 12:14

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0103_materialexchangesellorder_character_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="sdeblueprintactivity",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivity",
                    name="activity",
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivity",
                    name="eve_type",
                ),
                migrations.AlterUniqueTogether(
                    name="sdeblueprintactivitymaterial",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivitymaterial",
                    name="activity",
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivitymaterial",
                    name="eve_type",
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivitymaterial",
                    name="material_eve_type",
                ),
                migrations.AlterUniqueTogether(
                    name="sdeblueprintactivityproduct",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivityproduct",
                    name="activity",
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivityproduct",
                    name="eve_type",
                ),
                migrations.RemoveField(
                    model_name="sdeblueprintactivityproduct",
                    name="product_eve_type",
                ),
                migrations.RemoveField(
                    model_name="sdemarketgroup",
                    name="parent_market_group",
                ),
                migrations.DeleteModel(
                    name="SDESyncCompatState",
                ),
                migrations.DeleteModel(
                    name="SDEBlueprintActivity",
                ),
                migrations.DeleteModel(
                    name="SDEBlueprintActivityMaterial",
                ),
                migrations.DeleteModel(
                    name="SDEBlueprintActivityProduct",
                ),
                migrations.DeleteModel(
                    name="SDEIndustryActivity",
                ),
                migrations.DeleteModel(
                    name="SDEMarketGroup",
                ),
            ],
        ),
    ]
