# Generated by Django 4.2.27 on 2026-07-20

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0104_alter_sdeblueprintactivity_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionprojectitem",
            name="indy_hub_project_item_unique_type_category",
        ),
    ]
