# Generated by Django 5.2 on 2026-08-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0111_add_user_favorite_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndyHubUserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("total_usage_count", models.PositiveIntegerField(default=0)),
                ("activity_7d_count", models.PositiveIntegerField(default=0)),
                ("activity_30d_count", models.PositiveIntegerField(default=0)),
                ("daily_usage", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indy_hub_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Indy Hub usage",
                "verbose_name_plural": "Indy Hub usage",
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="indyhubuserusage",
            index=models.Index(
                fields=["last_used_at"], name="indy_usage_last_used_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="indyhubuserusage",
            index=models.Index(
                fields=["activity_30d_count"], name="indy_usage_30d_idx"
            ),
        ),
    ]
