# Generated by Django 5.2.1 on 2026-08-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0112_indyhubuserusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="indyhubuserusage",
            name="page_usage",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]