# Generated by Django 5.2 on 2026-08-08

# Django
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0112_indyhubuserusage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_character_id", models.BigIntegerField(blank=True, null=True)),
                ("main_character_name", models.CharField(blank=True, max_length=255)),
                ("corporation_id", models.BigIntegerField(blank=True, null=True)),
                ("corporation_name", models.CharField(blank=True, max_length=255)),
                ("scope_blueprints", models.BooleanField(default=False)),
                ("scope_jobs", models.BooleanField(default=False)),
                ("scope_assets", models.BooleanField(default=False)),
                ("scope_skills", models.BooleanField(default=False)),
                ("scope_online", models.BooleanField(default=False)),
                ("scope_complete", models.BooleanField(default=False)),
                ("scope_score", models.PositiveSmallIntegerField(default=0)),
                ("settings_score", models.PositiveSmallIntegerField(default=0)),
                ("notifications_enabled", models.BooleanField(default=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("activity_30d_count", models.PositiveIntegerField(default=0)),
                ("total_usage_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indy_hub_admin_status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin user status",
                "verbose_name_plural": "Admin user statuses",
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["main_character_name"], name="indy_admin_char_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["corporation_id"], name="indy_admin_corp_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["corporation_name"], name="indy_admin_corp_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["scope_complete"], name="indy_admin_scope_ok_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["last_used_at"], name="indy_admin_last_used_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["activity_30d_count"], name="indy_admin_activity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminuserstatus",
            index=models.Index(
                fields=["total_usage_count"], name="indy_admin_usage_idx"
            ),
        ),
    ]
