# Generated by Django 5.2 on 2026-08-08

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0113_adminuserstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="indyhubuserusage",
            name="rollup_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="IndyHubUsageDailyRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_day", models.DateField()),
                (
                    "page_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "page_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("usage_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_rollups",
                        to="indy_hub.indyhubuserusage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indy Hub daily usage rollup",
                "verbose_name_plural": "Indy Hub daily usage rollups",
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="indyhubusagedailyrollup",
            constraint=models.UniqueConstraint(
                fields=("usage", "usage_day", "page_key"),
                name="indy_usage_rollup_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="indyhubusagedailyrollup",
            index=models.Index(
                fields=["usage_day", "page_key"],
                name="indy_rollup_day_page_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="indyhubusagedailyrollup",
            index=models.Index(
                fields=["usage", "usage_day"],
                name="indy_rollup_usage_day_idx",
            ),
        ),
    ]
