[tox]
requires =
    tox>=4.2
env_list =
    py{312, 310}
skip_missing_interpreters = true

[testenv]
package = editable
deps =
    allianceauth
    allianceauth-app-utils>=1
    coverage
    django-esi<10,>=8
    django-eveonline-sde>=0.0.1
    django-webtest
set_env =
    DJANGO_SETTINGS_MODULE = testauth.settings.local
commands =
    coverage run runtests.py --verbosity=2

[testenv:py312]
commands =
    coverage run runtests.py --verbosity=2
    coverage report
    coverage xml
install_command = python -m pip install -U {opts} {packages}
